version: '{build}'

branches:
  only:
    - main

image:
  - Ubuntu2004

install:
  - ps: git submodule init
  - ps: git submodule update
  - ps: nproc
  - ps: pwd
  - ps: cd ~ && svn checkout -r 2974 https://svn.code.sf.net/p/tass64/code/trunk tass64-code
  - ps: cd ~/tass64-code && make

build_script:
  - ps: make VERBOSE=1 TASS=$HOME/tass64-code/64tass
    
